print("Installing Packages")
install.packages("leaps")
install.packages("earth")
install.packages("fields")
install.packages("/input/MultiMOVE_1.0.7.tar.gz", repos = NULL, type = "source")
source('/input/MM2.R')
